### ISSUE TITLE
cannot import name Counter

### ISSUE THREAD

**Issue by miguelballesteros** [mdtux89/amr-evaluation#1]
Hi, thanks for this tool.

When trying to evaluate a gold test set vs gold test set I get the following error message:
./evaluation.sh dev2014.txt  dev2014.txt 
Smatch -> P: 1.00, R: 1.00, F: 1.00
Unlabeled -> P: 1.00, R: 1.00, F: 1.00
No WSD -> P: 1.00, R: 1.00, F: 1.00
Traceback (most recent call last):
  File "scores.py", line 14, in <module>
    import smatch.smatch_edited as smatch
  File "/amr-evaluation/smatch/smatch_edited.py", line 15, in <module>
    import src.amr
  File "/amr-evaluation/smatch/src/amr.py", line 25, in <module>
    from collections import Counter
ImportError: cannot import name Counter

am I doing something wrong?
thanks!

**Comment by miguelballesteros** [comment]
just to add on this, the input was the LDC2014 dev set.

**Comment by mdtux89** [comment]
No, you're not doing anything wrong. That Counter import doesn't work for all python version but I actually don't need it anymore. Should be fixed now..
