### ISSUE TITLE
Data from the paper

### ISSUE THREAD

**Issue by mrmechko** [mdtux89/amr-evaluation#3]
Would it be possible to get the original data from the paper as a benchmark for trying out other similarity metrics?

**Comment by mdtux89** [comment]
The data from the paper is LDC2015E86, which I can't redistribute freely, afaik.

**Comment by mrmechko** [comment]
I've been looking for some way to replicate experiments on AMR similarity metrics and it really doesn't look like there is anything available.  Are you aware of any dataset which is at least available for purchase that has similarity annotations between structures?

**Comment by mdtux89** [comment]
If you are affiliated with a university, you may be able to get the LDC release. Otherwise, for AMR have a look here: https://amr.isi.edu. I'm not sure what you mean by "similarity annotations between structures".

**Comment by mrmechko** [comment]
2015E86 is DEFT only.  Apologies, I seem to have got my wires crossed.  I thought there was some human judgement involved to verify the quality of the modified smatch results.
